### ISSUE TITLE
Revive project and point MELPA at new upstream

### ISSUE THREAD

**Issue by mavit** [peterhoeg/ssh-config-mode-el#37]
There have been a few fairly straightforward pull requests backing up for several years now.  Sadly, I notice that @jhgorrell has no public activity on GitHub since 2021, and his website is down.  Perhaps we need someone to fork this project, if it is to continue development.

**Comment by mavit** [comment]
@peterhoeg: I see you have an up-to-date fork.  Should we contact MELPA, asking them to point at that?

**Comment by harley-hba** [comment]
Been busy with $DAYJOB -- Would be happy to xfer the repo or assist with a MELPA update.

**Comment by jhgorrell** [comment]
Been busy with $DAYJOB -- Would be happy to xfer the repo or assist with a MELPA update.

**Comment by peterhoeg** [comment]
I've been using my own fork for a while to scratch a few itches - I don't foresee a lot of changes, but there is definitely a few things we *can* do, and I'm happy to take over.

I'm not sure how to transfer a repo when a fork already exists. I can of course just delete it before @jhgorrell transfers it, but does anyone know a better way? Can a fork be marked as the new upstream?

I suggest we do the MELPA bit afterwards.

**Comment by jhgorrell** [comment]
My preference would be to:
- rename your repo to something else
- transfer this repo to you.

This would have the benefit that Github would have a "this repo has moved" link.
Otherwise future users would see mine, and then have to click through to yours.

**Comment by peterhoeg** [comment]
Sure, I have renamed it.

**Comment by jhgorrell** [comment]
Ugh -- looks like you cant have the same name or a clone.
I got the error: `peterhoeg already has a repository in the jhgorrell/ssh-config-mode-el network`

(see a related xfer: https://github.com/VeliovGroup/jazeee-meteor-spiderable/issues/45)

For now I added you as a collaborator while we figure this out.

**Comment by peterhoeg** [comment]
I've just blown mine away so a transfer should work now.

**Comment by jhgorrell** [comment]
The transfer is pending. 👍

**Comment by peterhoeg** [comment]
Transfer is complete, thanks for everything @jhgorrell.

@mavit, do you feel like doing a PR dance to get it changed at melpa?

**Comment by jhgorrell** [comment]
Most welcome!  Glad the mode will get some updates.

**Comment by mavit** [comment]
> do you feel like doing a PR dance to get it changed at melpa?

Will do!  Thanks, both.

**Comment by peterhoeg** [comment]
Thanks @mavit, melpa is now updated.
